In [42]:
import matplotlib.pyplot as plt
from statsmodels.base.model import GenericLikelihoodModel
import numpy as np
import cv2
import scienceplots
import tifffile as tiff

from boulder_statistics.analysis.data_product_encyclopedia import DataProductEncyclopedia
from boulder_statistics.analysis.fit_params.weibull_fit_params import WeibullFitParams

plt.style.use('science')
plt.rcParams["figure.figsize"] = (3.5, 3.5 * ((5**0.5 - 1) / 2)) # 3.5
plt.rcParams["figure.dpi"] = 600
%matplotlib inline

import polars as pl
from polars import Expr, LazyFrame, DataFrame
import numpy as np
from pathlib import Path
from typing import Any
import tifffile
from typing import Dict
from typing import Callable


from boulder_statistics.analysis.data_product_encyclopedia import DataProductEncyclopedia

dp = DataProductEncyclopedia(
    data_products_path=Path(r"C:\Users\Joshu\OneDrive - Nexus365\AO33\Boulder_database\AO33\.data_products"))

In [43]:
power_law_db = pl.read_parquet(r"MLE_random_sample_fit_data\PowerLaw")
weibull_db = pl.read_parquet(r"MLE_random_sample_fit_data\Weibull") # .filter(pl.col("k_err").is_not_nan())
log_normal_db = pl.read_parquet(r"MLE_random_sample_fit_data\LogNormal") # .filter(pl.col("mu_err").is_not_nan())

In [44]:
power_law_db

shape: (240, 15)
┌───────┬─────────────┬─────────────┬─────────────┬───┬───────────┬─────────┬───────┬──────────────┐
│ seed  ┆ aic         ┆ bic         ┆ numb_alphas ┆ … ┆ g_std_err ┆ LAD_min ┆ J_min ┆ min_alpha_to │
│ ---   ┆ ---         ┆ ---         ┆ ---         ┆   ┆ ---       ┆ ---     ┆ ---   ┆ _consider    │
│ i32   ┆ f64         ┆ f64         ┆ i64         ┆   ┆ f64       ┆ i32     ┆ f64   ┆ ---          │
│       ┆             ┆             ┆             ┆   ┆           ┆         ┆       ┆ f64          │
╞═══════╪═════════════╪═════════════╪═════════════╪═══╪═══════════╪═════════╪═══════╪══════════════╡
│ 39188 ┆ 2.6018e6    ┆ 2.6019e6    ┆ 192734      ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 100.0        │
│ 87298 ┆ 2.6057e6    ┆ 2.6057e6    ┆ 192734      ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 100.0        │
│ 24401 ┆ 2.6044e6    ┆ 2.6044e6    ┆ 192734      ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 100.0        │
│ 12872 ┆ 2.6041e6    ┆ 2.6042e6    ┆ 192734      ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 100.0        │
│ 43138 ┆ 2.5958e6    ┆ 2.5959e6    ┆ 192734      ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 100.0        │
│ …     ┆ …           ┆ …           ┆ …           ┆ … ┆ …         ┆ …       ┆ …     ┆ …            │
│ 56320 ┆ 8343.922225 ┆ 8367.657249 ┆ 386         ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 20000.0      │
│ 75733 ┆ 8344.671281 ┆ 8368.406306 ┆ 386         ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 20000.0      │
│ 84705 ┆ 8345.14717  ┆ 8368.882194 ┆ 386         ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 20000.0      │
│ 6977  ┆ 8352.732223 ┆ 8376.467247 ┆ 386         ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 20000.0      │
│ 93381 ┆ 8342.883395 ┆ 8366.618419 ┆ 386         ┆ … ┆ NaN       ┆ 0       ┆ 0.7   ┆ 20000.0      │
└───────┴─────────────┴─────────────┴─────────────┴───┴───────────┴─────────┴───────┴──────────────┘

In [45]:
columns_to_select = ["aic", "min_alpha_to_consider"]

aic_db = pl.concat([
    power_law_db.select(columns_to_select).with_columns(pl.lit("PL").alias("fit_type")),
    weibull_db.select(columns_to_select).with_columns(pl.lit("W").alias("fit_type")),
    log_normal_db.select(columns_to_select).with_columns(pl.lit("LN").alias("fit_type"))
]).filter(pl.col("min_alpha_to_consider") == 20000)

aic_db

shape: (240, 3)
┌─────────────┬───────────────────────┬──────────┐
│ aic         ┆ min_alpha_to_consider ┆ fit_type │
│ ---         ┆ ---                   ┆ ---      │
│ f64         ┆ f64                   ┆ str      │
╞═════════════╪═══════════════════════╪══════════╡
│ 8345.18332  ┆ 20000.0               ┆ PL       │
│ 8342.057548 ┆ 20000.0               ┆ PL       │
│ 8348.296266 ┆ 20000.0               ┆ PL       │
│ 8345.66443  ┆ 20000.0               ┆ PL       │
│ 8350.722825 ┆ 20000.0               ┆ PL       │
│ …           ┆ …                     ┆ …        │
│ 8343.345637 ┆ 20000.0               ┆ W        │
│ 8337.251908 ┆ 20000.0               ┆ W        │
│ 8343.460624 ┆ 20000.0               ┆ W        │
│ 8349.207858 ┆ 20000.0               ┆ W        │
│ 8341.410891 ┆ 20000.0               ┆ W        │
└─────────────┴───────────────────────┴──────────┘

In [46]:
aic_db = aic_db.join(
        aic_db.group_by("min_alpha_to_consider").agg(pl.col("aic").min().alias("min_aic_for_min_alpha_to_consider")),
        on = "min_alpha_to_consider",
    ).with_columns(
        (pl.col("aic") - pl.col("min_aic_for_min_alpha_to_consider")).alias("delta_aic")
    )

aic_db

shape: (240, 5)
┌─────────────┬───────────────────────┬──────────┬─────────────────────────────────┬───────────┐
│ aic         ┆ min_alpha_to_consider ┆ fit_type ┆ min_aic_for_min_alpha_to_consi… ┆ delta_aic │
│ ---         ┆ ---                   ┆ ---      ┆ ---                             ┆ ---       │
│ f64         ┆ f64                   ┆ str      ┆ f64                             ┆ f64       │
╞═════════════╪═══════════════════════╪══════════╪═════════════════════════════════╪═══════════╡
│ 8345.18332  ┆ 20000.0               ┆ PL       ┆ 8335.04626                      ┆ 10.13706  │
│ 8342.057548 ┆ 20000.0               ┆ PL       ┆ 8335.04626                      ┆ 7.011288  │
│ 8348.296266 ┆ 20000.0               ┆ PL       ┆ 8335.04626                      ┆ 13.250006 │
│ 8345.66443  ┆ 20000.0               ┆ PL       ┆ 8335.04626                      ┆ 10.61817  │
│ 8350.722825 ┆ 20000.0               ┆ PL       ┆ 8335.04626                      ┆ 15.676565 │
│ …           ┆ …                     ┆ …        ┆ …                               ┆ …         │
│ 8343.345637 ┆ 20000.0               ┆ W        ┆ 8335.04626                      ┆ 8.299377  │
│ 8337.251908 ┆ 20000.0               ┆ W        ┆ 8335.04626                      ┆ 2.205648  │
│ 8343.460624 ┆ 20000.0               ┆ W        ┆ 8335.04626                      ┆ 8.414365  │
│ 8349.207858 ┆ 20000.0               ┆ W        ┆ 8335.04626                      ┆ 14.161598 │
│ 8341.410891 ┆ 20000.0               ┆ W        ┆ 8335.04626                      ┆ 6.364631  │
└─────────────┴───────────────────────┴──────────┴─────────────────────────────────┴───────────┘

In [47]:
aic_db.group_by("fit_type").agg(
    pl.col("delta_aic").mean().alias("rel_mean_aic"),
    pl.col("delta_aic").std().alias("std_aic"),
    pl.col("delta_aic").min().alias("rel_min_aic"),
    pl.col("delta_aic").max().alias("rel_max_aic"),
    pl.len()
)

shape: (2, 6)
┌──────────┬──────────────┬──────────┬─────────────┬─────────────┬─────┐
│ fit_type ┆ rel_mean_aic ┆ std_aic  ┆ rel_min_aic ┆ rel_max_aic ┆ len │
│ ---      ┆ ---          ┆ ---      ┆ ---         ┆ ---         ┆ --- │
│ str      ┆ f64          ┆ f64      ┆ f64         ┆ f64         ┆ u32 │
╞══════════╪══════════════╪══════════╪═════════════╪═════════════╪═════╡
│ PL       ┆ 11.607725    ┆ 3.97288  ┆ 4.589144    ┆ 21.180794   ┆ 60  │
│ W        ┆ 7.535095     ┆ 4.001484 ┆ 0.0         ┆ 19.479685   ┆ 180 │
└──────────┴──────────────┴──────────┴─────────────┴─────────────┴─────┘

In [48]:
import polars as pl

types = aic_db["fit_type"].unique().sort().to_list()

samples = {
    t: aic_db.filter(pl.col("fit_type") == t)["delta_aic"].to_numpy()
    for t in types
}

for t in types:
    others = [o for o in types if o != t]

    a = samples[t]
    b = samples[others[0]]
    c = samples[others[1]]

    p = (
        (a[:, None, None] < b[None, :, None]) &
        (a[:, None, None] < c[None, None, :])
    ).mean()

    print(f"P(AIC {t} < ({others[0]}, {others[1]})) = {100*p:.3f}%")

IndexError: list index out of range